import { css } from "../../styled-system/css";

const scrollWrapper = css({
  margin: 0,
  padding: 0,
  top: "-1200px",
  left: "-400px",
  height: "200vh",
  width: "200vw",
  aspectRatio: "1/1",
  position: "absolute",
  display: "flex",
  gap: "200px",
  alignItems: "flex-start",
  justifyContent: "flex-start",
  flexDirection: "column",
  overflow: "hidden",
  transform: "rotate(-45deg)",
  // zIndex: -1,
});

const textScroll = {
  display: "flex",
  gap: 80,
  alignItems: "center",
};

const backgroundText = {
  color: "#000000",
  opacity: "5%",
  textAlign: "center",
  fontSize: 64,
  flexGrow: 1,
  flexShrink: 1,
};

export default function TextScroll() {
  return (
    <div class={scrollWrapper}>
      {Array.from({ length: 10 }).map((_, index) => {
        shuffleArray(wikipediaArticles);
        return (
          <div
            key={index}
            style={{
              animationName:
                index % 2 === 0 ? "scrollBackwards" : "scrollForward",
              animationDuration: `${randomInteger(wikipediaArticles.length * 16, wikipediaArticles.length * 18)}s`,
            }}
            class={css(textScroll, {
              animationTimingFunction: "linear",
              animationIterationCount: "infinite",
            })}
          >
            {wikipediaArticles.map((title, index2) => (
              <div key={index2} class={css(backgroundText)}>
                {title}
              </div>
            ))}
          </div>
        );
      })}
    </div>
  );
}

function shuffleArray<T>(array: T[]) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    //@ts-ignore
    [array[i], array[j]] = [array[j], array[i]];
  }
}

function randomInteger(min: number, max: number) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

const wikipediaArticles = [
  "Abraham Lincoln",
  "Ada Lovelace",
  "Albert Einstein",
  "Alexander Graham Bell",
  "Alfred Nobel",
  "Amelia Earhart",
  "Anne Frank",
  "Antarctica",
  "Apollo 11",
  "Aristotle",
  "Astronomy",
  "Audrey Hepburn",
  "Australia",
  "Babe Ruth",
  "Barack Obama",
  "Beethoven",
  "Benjamin Franklin",
  "Berlin",
  "Bill Gates",
  "Black Hole",
  "Brazil",
  "British Empire",
  "Canada",
  "Charles Darwin",
  "Charles Dickens",
  "Chemistry",
  "China",
  "Cleopatra",
  "Climate Change",
  "Computer Science",
  "Cristiano Ronaldo",
  "DNA",
  "Dalai Lama",
  "Daniel Defoe",
  "David Bowie",
  "Dinosaurs",
  "Earth",
  "Eleanor Roosevelt",
  "Elizabeth I",
  "Emily Dickinson",
  "England",
  "Ernest Hemingway",
  "F. Scott Fitzgerald",
  "Florence Nightingale",
  "France",
  "Freddie Mercury",
  "Galileo Galilei",
  "Gandhi",
  "Geography",
  "George Washington",
  "Germany",
  "Greece",
  "Harry Houdini",
  "Hawaii",
  "Hedy Lamarr",
  "Helen Keller",
  "Hermann Hesse",
  "Hillary Clinton",
  "History",
  "Isaac Newton",
  "Italy",
  "Jackie Robinson",
  "Jane Austen",
  "Japan",
  "Jimi Hendrix",
  "Joan of Arc",
  "John F. Kennedy",
  "John Lennon",
  "Julius Caesar",
  "Katherine Johnson",
  "Leonardo da Vinci",
  "Lewis Carroll",
  "Literature",
  "Louis Pasteur",
  "Madame Curie",
  "Mahatma Gandhi",
  "Marilyn Monroe",
  "Mark Twain",
  "Mars",
  "Martin Luther King Jr.",
  "Mary Shelley",
  "Mathematics",
  "Maya Angelou",
  "Michael Jackson",
  "Michelangelo",
  "Microsoft",
  "Mona Lisa",
  "Mozart",
  "Napoleon",
  "Neil Armstrong",
  "Netherlands",
  "New Zealand",
  "Nicolaus Copernicus",
  "Nikola Tesla",
  "Norway",
  "Nostradamus",
  "Orson Welles",
  "Pablo Picasso",
  "Pakistan",
  "Paris",
  "Pele",
  "Philosophy",
  "Physics",
  "Plato",
  "Poland",
  "Pythagoras",
  "Queen Elizabeth II",
  "Queen Victoria",
  "Renaissance",
  "Richard Nixon",
  "Rosa Parks",
  "Russia",
  "Salvador Dali",
  "Scotland",
  "Shakespeare",
  "Sigmund Freud",
  "Socrates",
  "Spain",
  "Stephen Hawking",
  "Steve Jobs",
  "Sweden",
  "Switzerland",
  "Tesla",
  "The Beatles",
  "Theodore Roosevelt",
  "Thomas Edison",
  "Thomas Jefferson",
  "Titanic",
  "Tolkien",
  "Ukraine",
  "United Kingdom",
  "United Nations",
  "United States",
  "Van Gogh",
  "Venezuela",
  "Vincent van Gogh",
  "Virginia Woolf",
  "Vladimir Lenin",
  "Voltaire",
  "Walt Disney",
  "Winston Churchill",
  "Wolfgang Amadeus Mozart",
  "Wright Brothers",
  "Yuri Gagarin",
  "Zelda Fitzgerald",
  "Zeus",
  "Zulu Kingdom",
  "Zoroaster",
  "Zoroastrianism",
  "Zulu",
  "Zombie",
  "Zoology",
  "Zoom Video Communications",
  "Zuccotti Park",
  "Zucchini",
  "Zug",
  "Zumba",
  "Zurich",
  "Zygote",
  "Zyrtec",
  "Zyzzyva",
  "ZZ Top",
  "Zymurgy",
  "Zynga",
  "Zion National Park",
  "Zero",
  "Zeppelin",
  "Zappa",
  "Zambezi",
  "Zamboni",
  "Artificial Intelligence",
  "Astrophysics",
  "Ayn Rand",
  "Bach",
  "Bacteria",
  "Baroque",
  "Bermuda Triangle",
  "Big Bang",
  "Biochemistry",
  "Biology",
  "Black Death",
  "Blues",
  "Bob Dylan",
  "Bram Stoker",
  "Bruce Lee",
  "Buddhism",
  "C. S. Lewis",
  "Cancer",
  "Carl Jung",
  "Carl Sagan",
  "Catherine the Great",
  "Charles Babbage",
  "Charlie Chaplin",
  "Che Guevara",
  "Chile",
  "Christianity",
  "Christopher Columbus",
  "Cloud Computing",
  "Cold War",
  "Confucius",
  "Cuban Missile Crisis",
  "Cybersecurity",
  "Da Vinci Code",
  "Dan Brown",
  "Data Science",
  "David Attenborough",
  "Davy Crockett",
  "Deep Learning",
  "Democracy",
  "Denmark",
  "Desmond Tutu",
  "Diana, Princess of Wales",
  "Digital Marketing",
  "Dolly Parton",
  "Dostoevsky",
  "Dr. Seuss",
  "Dungeons & Dragons",
  "Earthquake",
  "Easter Island",
  "Ecology",
  "Eddie Van Halen",
  "Edgar Allan Poe",
  "Edith Piaf",
  "Einstein",
  "El Salvador",
  "Electricity",
  "Elvis Presley",
  "Emily Bronte",
  "Engineering",
  "Ernest Shackleton",
  "Eva Peron",
  "Fidel Castro",
  "Fibonacci",
  "Frankenstein",
  "Frank Lloyd Wright",
  "Frida Kahlo",
  "Friedrich Nietzsche",
  "Galapagos Islands",
  "Galileo",
  "Genetics",
  "George Orwell",
  "Giza Pyramids",
  "Glacier",
  "Grace Hopper",
  "Great Wall of China",
  "Greek Mythology",
  "Guatemala",
  "Guglielmo Marconi",
  "Gustave Eiffel",
  "H.G. Wells",
  "Haiti",
  "Hemingway",
  "Henry Ford",
  "Herman Melville",
  "Hernan Cortes",
  "Hinduism",
  "History of the Internet",
  "Honduras",
  "Iceland",
  "Indonesia",
  "Industrial Revolution",
  "Internet",
  "Inventions",
  "Ireland",
  "Isaac Asimov",
  "Jack the Ripper",
  "James Clerk Maxwell",
  "James Cook",
  "James Watt",
  "Jane Goodall",
  "Jesse Owens",
  "Johannes Kepler",
  "John Keats",
  "John Steinbeck",
  "Jorge Luis Borges",
  "Joseph Stalin",
  "Juan Ponce de Leon",
  "Jules Verne",
  "K2",
  "Karl Marx",
  "Kazakhstan",
  "Kenya",
  "Kilimanjaro",
  "King Arthur",
  "Kurt Vonnegut",
  "Lance Armstrong",
  "Langston Hughes",
  "Leonard Cohen",
  "Levi Strauss",
  "Lichtenstein",
  "Lithuania",
  "Machu Picchu",
  "Madagascar",
  "Mark Zuckerberg",
  "Martha Graham",
  "Mauritania",
  "Maya Civilization",
  "Mayan Calendar",
  "Mexico",
  "Microbiology",
  "Mikhail Gorbachev",
  "Mongolia",
  "Mount Everest",
  "Mount Fuji",
  "Namibia",
  "Neil deGrasse Tyson",
  "Nepal",
  "New Guinea",
  "Newton",
  "Niels Bohr",
  "Nigeria",
  "Nuclear Power",
  "Octavio Paz",
  "Okinawa",
  "Optics",
  "Orlando",
  "Osmosis",
  "Otto von Bismarck",
  "Pacific Ocean",
  "Pablo Neruda",
  "Paleontology",
  "Panama Canal",
  "Pangaea",
  "Papua New Guinea",
  "Particle Physics",
  "Paul Gauguin",
  "Paul McCartney",
  "Peru",
  "Philippines",
  "Photosynthesis",
  "Ptolemy",
  "Puerto Rico",
  "Quantum Mechanics",
  "Queen",
  "Rainer Maria Rilke",
  "Ramses II",
  "Raphael",
  "Richard Feynman",
  "Robotics",
  "Rome",
  "Ronald Reagan",
  "San Francisco",
  "San Marino",
  "Sao Paulo",
  "Saturn",
  "Scandinavia",
  "Science Fiction",
  "Sculpture",
  "Seychelles",
  "Sherlock Holmes",
  "Silicon Valley",
  "Singapore",
  "Sistine Chapel",
  "Solar System",
  "Somalia",
  "South Africa",
  "South Pole",
  "Soviet Union",
  "Space Exploration",
  "Sri Lanka",
  "Statue of Liberty",
  "Stephen King",
  "Stock Market",
  "Sudan",
  "Taj Mahal",
  "Tanzania",
  "Tasmania",
  "Tchaikovsky",
  "Tennessee Williams",
  "Thailand",
  "Thomas More",
  "Time Travel",
  "Togo",
  "Tom Hanks",
  "Tornado",
  "Trinidad and Tobago",
  "Trojan War",
  "Tulip Mania",
  "Turkey",
  "Tutankhamun",
  "Uluru",
  "Uruguay",
  "Vatican City",
  "Vera Rubin",
  "Vesuvius",
  "Vietnam",
  "Vikings",
  "Volcano",
  "Walt Whitman",
  "War and Peace",
  "Warsaw",
  "Weather",
  "Wimbledon",
  "Wind Energy",
  "World War I",
  "World War II",
  "Yosemite",
  "Yukon",
  "Zimbabwe",
];
